build:
  script:
  - ./compile_googletest.sh
  - ./compile.sh
  - ./build/bin/main_tests
  after_script:
  - cd /media/storage/gitlab/
  - sudo rm -rf GoogleTest_Conan_Example
  - git clone http://git.home.lan/root/GoogleTest_Conan_Example.git
