build:
  script:
  - cd /media/storage/gitlab/
  after_script:
  - cd /media/storage/gitlab/
  - sudo rm -rf GoogleTest_Conan_Example
  - git clone http://192.168.109.15/root/GoogleTest_Conan_Example.git
